### ISSUE TITLE
trulyexpensesyoutube-master\authentication\views.py - line 9, 

### ISSUE THREAD

**Issue by rajeshdutta2000** [CryceTruly/trulyexpensesyoutube#8]
No module name validate email (module not found error)

**Comment by SinfoniNot** [comment]
> No module name validate email (module not found error)

Could you please tell me how you solved this problem? I'm having the same issue.

**Comment by rajeshdutta2000** [comment]
this is just a package you have to install using "pip install [package name]"  look at the stackoverflow article below
https://stackoverflow.com/questions/60332221/modulenotfounderror-no-module-named-validate-email

**Comment by SinfoniNot** [comment]
Thanks! By the way, were you able to get this project to work? I'm still having issues with it. I was wondering, which version of Django are you using for this? I'm using the latest version, but I'm starting to feel I need to downgrade.

**Comment by rajeshdutta2000** [comment]
No I couldn't as this project isn't a complete one,
